name:                twoD
version:             0.1.0.0
github:              "bewakes/twoD"
license:             BSD3
author:              "Bibek Pandey"
maintainer:          "bewakepandey@gmail.com"
copyright:           "2019 Bibek Pandey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bewakes/twoD#readme>

dependencies:
- base >= 4.7 && < 5
- random == 1.1
- gloss >= 1.10 && < 2
- glut >= 2.7.0

library:
  source-dirs: src

executables:
  twoD-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twoD

tests:
  twoD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twoD
